### ISSUE TITLE
Compatibility with featuretools 1.0.0

### ISSUE THREAD

**Issue by VGODIE** [alteryx/featuretools-tsfresh-primitives#88]
Is featuretools[tsfresh] compatible with featuretools 1.0.0 ?
I've got an error trying importing it as from featuretools.tsfresh import ...
The error is following `ModuleNotFoundError: No module named 'featuretools.tsfresh'`

**Comment by gsheni** [comment]
@VGODIE yes, this library does work with `featuretools>=1.0.0`. 
1. You can do the following to install:
```bash
pip install featuretools --upgrade
pip install featuretools-tsfresh-primitives
```

2. Can you do a `pip check` to verify there isn't any version conflicts?

3. For your import statements, you can directly import the tsfresh primitives. For example:
```python
from featuretools_tsfresh_primitives import AggAutocorrelation
```
